### ISSUE TITLE
Social Sharing - Not Pulling in Post Data

### ISSUE THREAD

**Issue by metastange** [wdetdigital/wdet-conversion#109]
When uploading urls to social scheduling and social platforms, the headline and excerpt are not pulled in. Instead, the headline reads "WDET 101.9FM WDET is Detroit' Public Radio Station" and "WDET is Detroit's Public Radio Station. For over 60 years, WDET has provided an independent voice for Detroit through a mix of news, music and cultural programming that's unique as the city and…" The image is populating.

![Screen Shot 2022-01-10 at 12 28 59 PM](https://user-images.githubusercontent.com/85897115/148811107-2172dbb8-fd24-47d8-b773-860485eaa084.png)
<img width="732" alt="Screen Shot 2022-01-10 at 12 30 19 PM" src="https://user-images.githubusercontent.com/85897115/148811301-8cde41c5-32ae-4106-973c-584ba982e4e1.png">

**Comment by artlogic** [comment]
I'm not seeing any linking data for social networks in posts - I would imagine there's a plugin for this - let's wait for @wdet30 on this one.

**Comment by metastange** [comment]
FYI, another iteration of this is in tabs - every tab has the same preview.

**Comment by metastange** [comment]
this is impacting our ability to post on social and share links - can we prioritize this issue tomorrow? @wdet30

**Comment by wdet30** [comment]
I hope to have a solution Thursday. I'm working on it tonight.

Thanks TB
________________________________

**Comment by wdet30** [comment]
@metastange, testing I should have something soon.

**Comment by wdet30** [comment]
@dorothyhernandez @metastange Sorry, this is taking so long. You will see that I'm testing social sharing tools and trying to resolve our meta data issues.

Sorry for the delay.

**Comment by metastange** [comment]
@wdet30 Is this related to what you're working on to pull in metadata or a separate issue?
<img width="1166" alt="Screen Shot 2022-01-14 at 10 17 35 AM" src="https://user-images.githubusercontent.com/85897115/149539194-3ec36f2c-ffe0-4460-aeed-cc9f8cd59eff.png">

**Comment by wdet30** [comment]
Yes, @Meta ***@***.***> definitely not the solution it's where I left off. I'll be pulling those down and circling back to this issue later on tonight or throughout the day. I'm still having trouble cobbling the metadata and passing it over to aggregators or social media. Sorry for the delay.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
Are tests being done in production? I can prioritize getting dev set up if that's needed.

**Comment by wdet30** [comment]
Let's get rolling on that. I will hold off test and dev until we get dev setup and cloned.

Thank you @***@***.******@***.***>

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dorothyhernandez** [comment]
The headlines and excerpts are now being pulled in for social posts.

**Comment by dorothyhernandez** [comment]
Reopening because when I try to post links in Teams, the copy says "WDET 101.9FM WDET is Detroit's Public Radio Station where it would usually have the headline. 

What it used to look like:
<img width="756" alt="Screen Shot 2022-01-18 at 2 10 06 PM" src="https://user-images.githubusercontent.com/91985309/150002839-40318657-d8ee-4503-bbf5-83ea4035771b.png">

What it looks like now:
<img width="753" alt="Screen Shot 2022-01-18 at 2 09 36 PM" src="https://user-images.githubusercontent.com/91985309/150002772-352eb192-31dd-4009-9322-465f3aeb567c.png">

**Comment by artlogic** [comment]
Removing myself for now - let me know if you need a hand @wdet30.

**Comment by dorothyhernandez** [comment]
When uploading urls to social scheduling and social platforms, the image pulled in is the author photo and not the featured image. Not sure if that is a website issue but flagging it here because prior to the launch of the new site this was never an issue. 

<img width="685" alt="Screen Shot 2022-01-21 at 7 52 37 PM" src="https://user-images.githubusercontent.com/91985309/150617853-f968fe18-908b-475d-b8db-5cc24b27463d.png">

**Comment by dorothyhernandez** [comment]
Per the Web Launch Status meeting 01.24.22, I am flagging the top 3 priorities. This is one of them.

**Comment by dorothyhernandez** [comment]
Per the Web Launch Status meeting 01.24.22, I am flagging the top 3 priorities. This is one of them.

**Comment by artlogic** [comment]
@wdet30 has indicated the new theme will resolve this - are we ready for testing on wdetdev yet?

**Comment by wdet30** [comment]
Resolved please see screenshot. 
![screen2281](https://user-images.githubusercontent.com/84190532/151753460-6bf6f3a9-7d96-4afd-99fc-cf7d08f9363b.png)

**Comment by dorothyhernandez** [comment]
Reopening this because the issue is not resolved. Author's image still being pulled in instead of the featured image. Please see screenshot of what it looks like in Buffer, which is what we use to schedule posts. Note: This is not related to posting links directly in the Facebook platform, which is another issue but I want to resolve this one first..

<img width="678" alt="Screen Shot 2022-04-28 at 5 45 41 PM" src="https://user-images.githubusercontent.com/91985309/165851656-4eea9f9d-a3ea-4011-a0a8-0945f46f7f09.png">

**Comment by dmsanderswdet** [comment]
Hi Tony,

Why are you assigning #109 to me?


Diane M. Sanders, MBA

Executive Assistant/Internship Coordinator

***@***.***

(o) 313-577-3039

4600 Cass Avenue

Detroit, MI  48201



Listen Live at  wdet.org<http://www.wdet.org/> or in the WDET mobile app<https://wdet.org/mobile/>

[cid:5088abf5-2547-42cb-878c-f043261c9670]

________________________________

**Comment by dorothyhernandez** [comment]
Dropping in this feedback re: posts on Twitter not pulling in post data. Photo is not showing up when links are shared.

<img width="581" alt="Screen Shot 2022-06-02 at 9 56 26 AM" src="https://user-images.githubusercontent.com/91985309/171645853-3a3fdbc5-52ee-485a-aa26-4f7d85537f33.png">
