### ISSUE TITLE
Font Breakdown

### ISSUE THREAD

**Issue by wdet30** [wdetdigital/wdet-conversion#67]
}

h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 {
  font-family: "Gotham SSm A", "Gotham SSm B", "Gill Sans", Helvetica, Arial, sans-serif;
  font-weight: 700;
  line-height: 1.1;
  color: #272727;
}

.site-header {
  font-family: "Gotham SSm A", "Gotham SSm B", "Gill Sans", Helvetica, Arial, sans-serif;
}

"Source Sans Pro", "Gill Sans", Helvetica, Arial, sans-serif;

body {
    font-family: "Source Sans Pro", "Gill Sans", Helvetica, Arial, sans-serif;
}

**Comment by wdet30** [comment]
@metastange , it look like the font type issues has been resolved. Would you please give a look and note any Font type issues? 

Here is what is coded:
(Headers)
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 
 "Gotham SSm A", "Gotham SSm B", "Gill Sans", Helvetica, Arial, sans-serif;

Body
body (p)
"Source Sans Pro", "Gill Sans", Helvetica, Arial, sans-serif;

Right now only looking at the font type

**Comment by metastange** [comment]
@wdet30 I'm not seeing font changes on my end; the headers are not gotham. Do I need to do anything different to see the updates?

**Comment by wdet30** [comment]
Ok thanks for the update. I will hope can resolve this Tuesday.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wdet30** [comment]
@artlogic @metastange the font issues has been resolved. Please see the attached screen shots on what's computed on my end.
![font2](https://user-images.githubusercontent.com/84190532/141123124-cb2b684f-0579-41fe-a767-619e238af13c.png)
![Font1_](https://user-images.githubusercontent.com/84190532/141123381-63bc0f95-c2ec-4dca-a183-54075c9c3f58.jpg)

**Comment by metastange** [comment]
What do I need to do to see this on my end? Still not populating on the front-end for me.

**Comment by metastange** [comment]
Cleared my history, checked in an incognito browser and still no dice.

@dorothyhernandez can you check this one on your end too?

**Comment by wdet30** [comment]
@artlogic, would you please check what fonts are loaded on layout and show what you are computing.

Thanks,

**Comment by metastange** [comment]
Just came across something weird - the fonts still aren't populating correctly for me on the site, but when i copied and pasted something into a doc, it was the correct font. Not sure if this information helps diagnose the problem, just wanted to let you know!

**Comment by wdet30** [comment]
Thanks for this information.




________________________________

**Comment by artlogic** [comment]
Could I get some clarification on what you need me to confirm?

**Comment by wdet30** [comment]
Can you let me know what fonts are being called into your browser on the headers and the paragraph what are you actually computing

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by artlogic** [comment]
I'm not seeing a problem with the computed fonts, but I don't think everyone will have those specific fonts available.

**Comment by wdet30** [comment]
Copy,
Thanks
________________________________

**Comment by metastange** [comment]
Bulleted fonts are bolded; they should be the same as paragraph/body. I don't know if this is an issue because fonts still aren't populating correctly for me or what, just wanted to flag that in case those issues are unrelated.

**Comment by wdet30** [comment]
Got this down as a note I'm going to be redrawing the font calls over the weekend hopefully this will resolve this issue.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by metastange** [comment]
FYI this is still not populating for me correctly; i have cleared my cache and tried in multiple browsers. Let me know if there are additional steps I need to take.
![Screen Shot 2021-12-01 at 10 06 04 AM](https://user-images.githubusercontent.com/85897115/144259535-477afa14-7ba9-4348-9314-27939f02a8de.png)

**Comment by metastange** [comment]
This issue has not been resolved; fonts that should be gotham on both the new site and, now, on the old site are populating as Gill Sans (screenshots attached).

Our graphic designer says she has found an error and is going to send details via email; will post here once I have that note.
<img width="1234" alt="Screen Shot 2022-01-05 at 12 24 16 PM" src="https://user-images.githubusercontent.com/85897115/148261255-4a33c325-e90c-460e-833a-c4d9bf46effd.png">
<img width="1428" alt="Screen Shot 2022-01-05 at 12 25 06 PM" src="https://user-images.githubusercontent.com/85897115/148261365-f24298c5-c621-4442-aa21-705e0a24f44e.png">

**Comment by artlogic** [comment]
Can you point out the specific font? Maybe circle it in the image?

**Comment by metastange** [comment]
All of the blue font in the second image.
<img width="1095" alt="Screen Shot 2022-01-05 at 12 51 43 PM" src="https://user-images.githubusercontent.com/85897115/148265071-7deaa870-ad9e-4091-a216-3778399baa72.png">

**Comment by artlogic** [comment]
Thank you. I should be able to look into this in an hour or two. Let me know what your graphic designer says

**Comment by artlogic** [comment]
Gothan is not a free font. In order to have it included in the site you'll need to purchase a license from typography.com: https://www.typography.com/fonts/gotham/styles

You'll have to choose a license for websites based on your monthly page views and the styles of Gothan you need. Licensing is yearly.

**Comment by metastange** [comment]
@wdet30 Gotham was used on the site until about three weeks ago - do you have any information on previously-purchased licenses?

**Comment by wdet30** [comment]
I will look around but not that I know of
________________________________

**Comment by artlogic** [comment]
@metastange did you happen to receive a new computer?

**Comment by metastange** [comment]
I did in fact get a new computer. But this problem is showing up for @dorothyhernandez as well, who is on the same machine she has been on (screenshots below):
<img width="947" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/85897115/148410171-c2667be6-50e0-40be-90df-8b5ec25bcb9e.png">
<img width="1002" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/85897115/148410173-e3009e19-d2d7-43b5-ab84-be045f65b6e5.png">

**Comment by artlogic** [comment]
I suspect your old computer had Gotham installed and your new computer does not. There's no sign of a web font reference that I can find on the old or new sites.

Has @dorothyhernandez seen a change in fonts, or have they simply not been Gotham ever?

**Comment by dorothyhernandez** [comment]
I have seen a change in fonts. A couple of weeks ago (sorry, I didn't document the actual date) I noticed the current site had switched over to Gill Sans after it had been Gotham. I've had the same computer since I started in March 2021 so it's not machine related.

**Comment by wdet30** [comment]
We don't have a license for the font it seems.

**Comment by artlogic** [comment]
@dorothyhernandez do you have Gotham available as a font on your computer?

**Comment by metastange** [comment]
@artlogic FWIW I have gotham on my computer and this was ALSO brought up by our graphic designer who ALSO has gotham on her computer.

**Comment by dorothyhernandez** [comment]
@artlogic Yes, I have Gotham installed on my computer.

**Comment by artlogic** [comment]
There are a large number of variants - both websites request "Gotham SSm A" and then "Gotham SSm B". Do you both have those fonts installed? (Those are likely Screen Smart Medium - I'm not sure what the A or B stand for however).

**Comment by metastange** [comment]
@artlogic would you be able to discuss this with our designer? i feel like we're going in circles here and it's clear we're not articulating the issue as well as we could be. She can provide insight on what she's noticing on the old site and, hopefully, that will help you and @wdet30 diagnose the issue on the new site.

Let me know and I'll connect the two of you via email.

**Comment by artlogic** [comment]
I just looked at an archive of the site from July, and it is indeed using Gotham. I'm looking into this further.

**Comment by artlogic** [comment]
It looks like at one time you must have been paying for a license for Gotham. This appears on the old site: `<link rel="stylesheet" type="text/css" href="//cloud.typography.com/6616132/631866/css/fonts.css" />`

Now when I attempt to retrieve that file, it says the account has been deactivated.

The only legal way to get this font back is to pay for a yearly license. There's nothing else to be done.

**Comment by metastange** [comment]
We're working on reinstating the license. Thanks for your time on this.

**Comment by metastange** [comment]
The license has been renewed so fonts should now be populating correctly on the active site (it's working on my end).

Not sure what steps need to be taken to apply this license to the redesigned site - let me know if you need additional information from me to facilitate.

**Comment by wdet30** [comment]
Please move fonts into post launch. I just looked at how to setup.  Once the DNS points to the new site the fonts should work. Would you please verify that the Gotham fonts are working on the current site now? That will tell the story if there is any other integration needed post launch.

Thanks,
Tony


________________________________

**Comment by metastange** [comment]
Verified in the previous post. Added post-launch tag.

**Comment by wdet30** [comment]
Thanks! TB
________________________________

**Comment by artlogic** [comment]
We need to add the proper stylesheet from the old wdet.org from the proper Gotham font to be pulled down.

**Comment by artlogic** [comment]
I spent a bit of time looking at this, and it appears there's more to using typography.com than just that. I'll continue to look into this unless someone else would like to.

**Comment by codingforapps** [comment]
I added wdetdev.wdet.org into the project domains on typography.com and then inserted the CSS link into the header.php on the child theme in dev site. I waited for the fonts to propagate but they didn't. My next step is to call/email their support line.

**Comment by artlogic** [comment]
Thanks - I'll assign this directly to you.

**Comment by codingforapps** [comment]
From what i gathered from our conversation @artlogic the webfonts are not in the place we think they are? 

On typography.com, I was able to generate the zip file attached. 

Can you upload its contents to the server? specifically at:  

https://wdet.org/static/wdet/fonts

[841169.zip](https://github.com/arsmentis/wdet-conversion/files/8164186/841169.zip)

AND if you think they should be stored somewhere else totally, put them there, then tell me where so I can put the address into typography.com.

**Comment by artlogic** [comment]
Should I upload the zip file, or the contents of the zip?

**Comment by codingforapps** [comment]
Unpack and upload the folder actually. 

https://wdet.org/static/wdet/fonts/841176

Their phone# didnt work its actually confusing I'll still email them.
Confusing because you have to go back to step 1 after step 3 but then its asking you to regenerate new fonts 

It

**Comment by codingforapps** [comment]
this file
[841176.zip](https://github.com/arsmentis/wdet-conversion/files/8164301/841176.zip)

**Comment by artlogic** [comment]
I'll see about getting this done later tonight. I'm out of time to work on this for the afternoon.

**Comment by codingforapps** [comment]
in that case, since it'll log me out before i can confirm the installation.... i'm wondering if you can rename the folder to what it says below, that might work. 

<img width="803" alt="Screen Shot 2022-03-01 at 2 40 13 PM" src="https://user-images.githubusercontent.com/6656745/156237081-bcb021ca-6ad8-4c12-be29-4d15249427c1.png">

**Comment by artlogic** [comment]
I'll make sure to use that updated path, but I do think I'll have to change the URL a bit. I'll let you know.

**Comment by artlogic** [comment]
@codingforapps I've uploaded the proper files to dev. However, I had to change the path slightly. Let me know if this works:

https://wdetdev.wdet.org/media/static/wdet/fonts/841176

**Comment by codingforapps** [comment]
update: let's just do this together when we can later! 

the problem is their tool. we give the url (step1) before it produces the unique files (step2) for our server, then wants to verify their in place (step3) but it'll log me out if their not uploaded immanently... i cannot just do step1 or go back to step 1 without making unique files again... 

so my solution is to meet to decide where were putting them, generate, transfer to upload, verify in a meeting. 

<img width="805" alt="Screen Shot 2022-03-16 at 8 11 25 PM" src="https://user-images.githubusercontent.com/6656745/158711842-5ef59424-4f0f-4da1-bd4f-78d503bdb6aa.png">

**Comment by artlogic** [comment]
I understand - please let me know what works for you can we can do this on a call. Thanks.

**Comment by codingforapps** [comment]
Where we left off with this — James and i communicated in this thread that we'd work over a call to upload the fonts. That was right before he exited / involvement changed. I need this to be one of the specific things we have him work on. I'm unsure how we proceed with that, or who is responsible for managing James' work — if anyone can assist, I would be grateful.

**Comment by wdet30** [comment]
Ryan can help with getting work to James. Olu came up with the idea of sticking with standard web fonts. This sounds like a great idea. We would be able to close this ticket and move on.

T

Anthony Brown
WDET, Digital Distribution Manager
(o) 313-577-8748
www.wdet.org
[cid:bcd8ec6c-3809-436b-b688-254c28bff8ed]
________________________________

**Comment by dorothyhernandez** [comment]
Before this ticket is closed, will there be any discussion on my previous comment and question? Is getting Gotham impossible? I would strongly advocate for Gotham over web safe fonts because it is part of WDET's brand and identity. This particular font was chosen for its friendly, conversational qualities.

**Comment by wdet30** [comment]
Please feel free to keep the ticket open not going to close it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
